// <auto-generated />
using System;
using CashflowPilot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashflowPilot.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ActualRun", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CreatedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("EntryCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("ErrorMessage")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<int>("PortfolioId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ReportingPeriod")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("RunDate")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("UploadedFileId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_ActualRuns_OrganizationId");

                b.HasIndex("PortfolioId")
                    .HasDatabaseName("IX_ActualRuns_PortfolioId");

                b.HasIndex("UploadedFileId")
                    .HasDatabaseName("IX_ActualRuns_UploadedFileId");

                b.ToTable("ActualRuns");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.AuditLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Details")
                    .HasColumnType("TEXT");

                b.Property<string>("EntityId")
                    .HasColumnType("TEXT");

                b.Property<string>("EntityType")
                    .HasColumnType("TEXT");

                b.Property<string>("IpAddress")
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OrganizationId", "Timestamp")
                    .HasDatabaseName("IX_AuditLogs_OrganizationId_Timestamp");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.CashflowEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int?>("ActualRunId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("CapitalCalls")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Distributions")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<int>("EntryType")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ForecastRunId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("FundId")
                    .HasColumnType("INTEGER");

                b.Property<string>("FundName")
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Period")
                    .HasColumnType("TEXT");

                b.Property<int>("PortfolioId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("StrategyId")
                    .HasColumnType("INTEGER");

                b.Property<string>("StrategyName")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ActualRunId")
                    .HasDatabaseName("IX_CashflowEntries_ActualRunId");

                b.HasIndex("ForecastRunId")
                    .HasDatabaseName("IX_CashflowEntries_ForecastRunId");

                b.HasIndex("FundId")
                    .HasDatabaseName("IX_CashflowEntries_FundId");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_CashflowEntries_OrganizationId");

                b.HasIndex("PortfolioId")
                    .HasDatabaseName("IX_CashflowEntries_PortfolioId");

                b.HasIndex("StrategyId")
                    .HasDatabaseName("IX_CashflowEntries_StrategyId");

                b.ToTable("CashflowEntries");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.CommentaryPack", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AdditionalNotes")
                    .HasColumnType("TEXT");

                b.Property<string>("DelayedDistributions")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ExecutiveSummary")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("GeneratedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("GeneratedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("HigherThanExpectedCalls")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("NegativeVariances")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PositiveVariances")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("VarianceAnalysisId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Watchpoints")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_CommentaryPacks_OrganizationId");

                b.HasIndex("VarianceAnalysisId")
                    .IsUnique()
                    .HasDatabaseName("IX_CommentaryPacks_VarianceAnalysisId");

                b.ToTable("CommentaryPacks");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ForecastRun", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CreatedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("EntryCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("ErrorMessage")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<int>("PortfolioId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("RunDate")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("UploadedFileId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_ForecastRuns_OrganizationId");

                b.HasIndex("PortfolioId")
                    .HasDatabaseName("IX_ForecastRuns_PortfolioId");

                b.HasIndex("UploadedFileId")
                    .HasDatabaseName("IX_ForecastRuns_UploadedFileId");

                b.ToTable("ForecastRuns");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Fund", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AssetClass")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<int>("PortfolioId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("Vintage")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_Funds_OrganizationId");

                b.HasIndex("PortfolioId")
                    .HasDatabaseName("IX_Funds_PortfolioId");

                b.ToTable("Funds");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Organization", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("IX_Organizations_Name");

                b.ToTable("Organizations");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Portfolio", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseCurrency")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_Portfolios_OrganizationId");

                b.ToTable("Portfolios");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Scenario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("CallsAdjustmentPct")
                    .HasPrecision(10, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<decimal>("DistributionsAdjustmentPct")
                    .HasPrecision(10, 4)
                    .HasColumnType("TEXT");

                b.Property<int>("ForecastRunId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TimingShiftMonths")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ForecastRunId")
                    .HasDatabaseName("IX_Scenarios_ForecastRunId");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_Scenarios_OrganizationId");

                b.ToTable("Scenarios");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Strategy", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<int>("FundId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("FundId")
                    .HasDatabaseName("IX_Strategies_FundId");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_Strategies_OrganizationId");

                b.ToTable("Strategies");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.UploadedFile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ErrorMessage")
                    .HasColumnType("TEXT");

                b.Property<long>("FileSize")
                    .HasColumnType("INTEGER");

                b.Property<int>("FileType")
                    .HasColumnType("INTEGER");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<string>("OriginalFileName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("StoredFileName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UploadedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_UploadedFiles_OrganizationId");

                b.ToTable("UploadedFiles");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.VarianceAnalysis", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActualRunId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedByUserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("ForecastRunId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ActualRunId")
                    .HasDatabaseName("IX_VarianceAnalyses_ActualRunId");

                b.HasIndex("ForecastRunId")
                    .HasDatabaseName("IX_VarianceAnalyses_ForecastRunId");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_VarianceAnalyses_OrganizationId");

                b.ToTable("VarianceAnalyses");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.VarianceEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("ActualCapitalCalls")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<decimal>("ActualDistributions")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<decimal>("CumulativeVariance")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<decimal>("ForecastCapitalCalls")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<decimal>("ForecastDistributions")
                    .HasPrecision(18, 6)
                    .HasColumnType("TEXT");

                b.Property<int?>("FundId")
                    .HasColumnType("INTEGER");

                b.Property<string>("FundName")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Period")
                    .HasColumnType("TEXT");

                b.Property<int>("PortfolioId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("StrategyId")
                    .HasColumnType("INTEGER");

                b.Property<string>("StrategyName")
                    .HasColumnType("TEXT");

                b.Property<int>("VarianceAnalysisId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("VarianceAnalysisId")
                    .HasDatabaseName("IX_VarianceEntries_VarianceAnalysisId");

                b.ToTable("VarianceEntries");
            });

            modelBuilder.Entity("CashflowPilot.Infrastructure.Data.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<int>("OrganizationId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PasswordHash")
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("TEXT");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.HasIndex("OrganizationId")
                    .HasDatabaseName("IX_AspNetUsers_OrganizationId");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RoleId")
                    .HasDatabaseName("IX_AspNetRoleClaims_RoleId");

                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_AspNetUserClaims_UserId");

                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderKey")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_AspNetUserLogins_UserId");

                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId")
                    .HasDatabaseName("IX_AspNetUserRoles_RoleId");

                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("LoginProvider")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ActualRun", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Portfolio", "Portfolio")
                    .WithMany("ActualRuns")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Domain.Entities.UploadedFile", "UploadedFile")
                    .WithMany()
                    .HasForeignKey("UploadedFileId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Portfolio");
                b.Navigation("UploadedFile");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.CashflowEntry", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.ActualRun", "ActualRun")
                    .WithMany("CashflowEntries")
                    .HasForeignKey("ActualRunId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("CashflowPilot.Domain.Entities.ForecastRun", "ForecastRun")
                    .WithMany("CashflowEntries")
                    .HasForeignKey("ForecastRunId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("CashflowPilot.Domain.Entities.Fund", "Fund")
                    .WithMany("CashflowEntries")
                    .HasForeignKey("FundId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("CashflowPilot.Domain.Entities.Portfolio", "Portfolio")
                    .WithMany()
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Domain.Entities.Strategy", "Strategy")
                    .WithMany()
                    .HasForeignKey("StrategyId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("ActualRun");
                b.Navigation("ForecastRun");
                b.Navigation("Fund");
                b.Navigation("Portfolio");
                b.Navigation("Strategy");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.CommentaryPack", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.VarianceAnalysis", "VarianceAnalysis")
                    .WithOne("CommentaryPack")
                    .HasForeignKey("CashflowPilot.Domain.Entities.CommentaryPack", "VarianceAnalysisId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("GeneratedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("VarianceAnalysis");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ForecastRun", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Portfolio", "Portfolio")
                    .WithMany("ForecastRuns")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Domain.Entities.UploadedFile", "UploadedFile")
                    .WithMany()
                    .HasForeignKey("UploadedFileId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Portfolio");
                b.Navigation("UploadedFile");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Fund", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Portfolio", "Portfolio")
                    .WithMany("Funds")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Portfolio");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Portfolio", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Organization", "Organization")
                    .WithMany("Portfolios")
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Organization");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Scenario", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.ForecastRun", "ForecastRun")
                    .WithMany()
                    .HasForeignKey("ForecastRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ForecastRun");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Strategy", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Fund", "Fund")
                    .WithMany("Strategies")
                    .HasForeignKey("FundId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Fund");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.UploadedFile", b =>
            {
                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UploadedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.VarianceAnalysis", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.ActualRun", "ActualRun")
                    .WithMany()
                    .HasForeignKey("ActualRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Domain.Entities.ForecastRun", "ForecastRun")
                    .WithMany()
                    .HasForeignKey("ForecastRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ActualRun");
                b.Navigation("ForecastRun");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.VarianceEntry", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.VarianceAnalysis", "VarianceAnalysis")
                    .WithMany("Entries")
                    .HasForeignKey("VarianceAnalysisId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("VarianceAnalysis");
            });

            modelBuilder.Entity("CashflowPilot.Infrastructure.Data.ApplicationUser", b =>
            {
                b.HasOne("CashflowPilot.Domain.Entities.Organization", "Organization")
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Organization");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("CashflowPilot.Infrastructure.Data.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ActualRun", b =>
            {
                b.Navigation("CashflowEntries");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.ForecastRun", b =>
            {
                b.Navigation("CashflowEntries");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Fund", b =>
            {
                b.Navigation("CashflowEntries");
                b.Navigation("Strategies");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Organization", b =>
            {
                b.Navigation("Portfolios");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.Portfolio", b =>
            {
                b.Navigation("ActualRuns");
                b.Navigation("ForecastRuns");
                b.Navigation("Funds");
            });

            modelBuilder.Entity("CashflowPilot.Domain.Entities.VarianceAnalysis", b =>
            {
                b.Navigation("CommentaryPack");
                b.Navigation("Entries");
            });
#pragma warning restore 612, 618
        }
    }
}
